---
title: timber.io
timezone: UTC
collections:
  plans:
    title: Plans
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
desc: Timber.io – Make logging great again.
url: https://timber.io
baseurl: ''
email: jackal@gmail.com
author: The Jackal
twitter_username: clenemt
github_username: clenemt
github_source: jackal
google_analytics: UA-XXXXXXXX-X
paginate: 5
paginate_path: "/blog/page:num"
navigation:
- title: Home
  url: "/"
  desc: Logging made better
- title: Blog
  url: "/blog/"
  desc: Stuffs I write about
- title: Projects
  url: "/projects/"
  desc: Stuffs I like to do
- title: Work
  url: "/work/"
  desc: Stuffs I hate to do
- title: About
  url: "/about/"
  desc: Learn about me
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
include:
- _pages
exclude:
- README.md
- vendor
gems:
- jekyll-paginate
