---
title: timber.io
timezone: UTC
collections:
  plans:
    title: Plans
    output: true
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
    permalink: /blog/tag/:name/
  docs:
    title: Docs
    permalink: /docs/:path/
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: blog_tags
  values:
    layout: posts_by_tag
- scope:
    path: ''
    type: docs
  values:
    layout: docs
permalink: pretty
desc: Timber.io – Structured Logging Made Easy
url: https://timber.io
app_url: https://app.timber.io
baseurl: ''
email: hi@timber.io
author: Timber.io
logo: /assets/logo-square.png
twitter:
  username: timberdotio
social:
  name: Timber.io
  links:
    - https://twitter.com/timberdotio
    - https://www.facebook.com/timberdotio
    - https://www.linkedin.com/company/timber.io
    - https://github.com/timberio
github_username: timberio
github_source: timberio/timber-io
segment_key: ocCzUkf4zAaUOzyCbWelskTptGgenOAU
paginate: 5
paginate_path: "/blog/page:num"
navigation:
- title: Features
  url: "/features/"
  desc: Logging made better
- title: Pricing
  url: "/pricing/"
  desc: Different package deals
- title: About
  url: "/about/"
  desc: What Timber is about
- title: Docs
  url: "/docs/"
- title: Blog
  url: "/blog/"
  desc: Timber community posts
features:
- title: Modern Dashboard
  image: dashboard
  desc: Our lightning fas and flexible dashboard allows you to search through your
    logs with ease.
- title: Real-Time Tailing
  image: realtime
  desc: All logs are pushed to your dashboard in real-time, no batched updates, pure
    speed.
- title: <em>Fast</em> Searching & Filtering
  image: search
  desc: We allow you to search and filter logs by user, resource, request type, or
    any other context you can think of.
- title: Clickable Logs
  image: logs
  desc: Since we intelligently parse your logs, we can identify important chunks and
    let you click between them. Mind blown.
- title: 6 Month Retention
  image: retention
  desc: Most services keep your logs for 2 weeks, we start out with 6 month retention
    by default at no extra charge.
- title: Log-based Graphing
  image: trending
  desc: Easily identify outliers, memory spikes and trending events with our advanced
    facets and graphs.
- title: 1 Click Heroku Install
  image: install
  desc: Just install our package and logs will automatically be parsed and sent to
    your dashboard, no configuration necessary.
billing_plans:
- name: Free
  image: free-plan
  price: 0
  data: 100MB
- name: Personal
  image: personal-plan
  price: 10
  data: 1GB
- name: Team
  image: team-plan
  price: 68
  data: 8GB
- name: Enterprise
  image: enterprise-plan
  price: 350+
  data: 50GB+
faqs:
- title: How does it work?
  desc: Once the Timber package or gem is installed, it will automatically decorate your logs with useful context and events (user info, requests, queries, etc).
- title: How do I install Timber?
  desc: Simply sign up and choose your language and platform, from there you will be guided through a very brief installation process that will give you everything you need.
- title: How much does it cost?
  desc: Timber offers a variety of plans (including a generous free tier) to suit any company size. Paid plans start at $8 per GB of data sent.
- title: Which apps do you support?
  desc: Currently we have packages for ruby, elixir and node, but can also accept logs from any app that runs on Heroku.
- title: What data can I collect?
  desc: You can see all of the possible fields at https://github.com/timberio/log-event-json-schema, but you can also add your own custom context and events.
- title: How is this different?
  desc: Most logging platforms accept only raw text or json payloads. Timber automatically structures your logs so they're consistent, and augments them with custom context and events.
team:
- name: Zach Sherman
  image: zach
  role: Founder & CEO
  desc: Founder @timberdotio, previously @seatgeek. @VanderbiltU grad. I like programming, design & sushi.
- name: Ben Johnson
  image: ben
  role: Founder & CTO
  desc: Founder / CTO @timberdotio, previously @seatgeek. I do things with computers.
- name: David Antaramian
  image: david
  role: Senior Backend Engineer
  desc: A curmudgeon that codes in @elixirlang and sometimes Ruby. Senior Backend Engineer at @timberdotio. Organizing @ElixirNYC. Treasuring @empexco.
- name: Garet McKinley
  image: garet
  role: Frontend Engineer
  desc: Writer of software. Designer of Vectors. Open source lover.
- name: You?
  image: bronson
  role: Lumberjack
  desc: Interested in working at Timber? Send us an email at <a href="mailto:hi@timber.io">hi@timber.io</a>.
footer:
- title: Features
  url: "/features/"
  desc: Logging made better
- title: Pricing
  url: "/pricing/"
  desc: Different package deals
- title: About
  url: "/about/"
  desc: What Timber is about
- title: Contact
  url: mailto://hi@timber.io
  desc: How to reach us
- title: Blog
  url: "/blog/"
  desc: Timber community posts
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
include:
- _pages
exclude:
- README.md
- vendor
gems:
- jekyll-paginate
- jekyll-seo-tag
