---
title: timber.io
timezone: UTC
collections:
  plans:
    title: Plans
    output: true
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
    permalink: /blog/tag/:name/
  docs:
    title: Docs
    permalink: /docs/:path/
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: blog_tags
  values:
    layout: posts_by_tag
- scope:
    path: ''
    type: docs
  values:
    layout: docs
permalink: pretty
desc: Timber.io – Structured Logging Made Easy
url: https://timber.io
baseurl: ''
email: hi@timber.io
author: Timber.io
logo: /assets/logo-square.png
twitter:
  username: timberdotio
social:
  name: Timber.io
  links:
    - https://twitter.com/timberdotio
    - https://www.facebook.com/timberdotio
    - https://www.linkedin.com/company/timber.io
    - https://github.com/timberio
github_username: timberio
github_source: timberio/timber-io
segment_key: ocCzUkf4zAaUOzyCbWelskTptGgenOAU
paginate: 5
paginate_path: "/blog/page:num"
navigation:
- title: Features
  url: "/features/"
  desc: Logging made better
- title: Pricing
  url: "/pricing/"
  desc: Different package deals
- title: About
  url: "/about/"
  desc: What Timber is about
- title: Docs
  url: "/docs/"
- title: Blog
  url: "/blog/"
  desc: Timber community posts
features:
- title: Modern Dashboard
  image: dashboard
  desc: Our lightning fas and flexible dashboard allows you to search through your
    logs with ease.
- title: Real-Time Tailing
  image: realtime
  desc: All logs are pushed to your dashboard in real-time, no batched updates, pure
    speed.
- title: Fast Searching & Filtering
  image: search
  desc: We allow you to search and filter logs by user, resource, request type, or
    any other context you can think of.
- title: Clickable Logs
  image: logs
  desc: Since we intelligently parse your logs, we can identify important chunks and
    let you click between them. Mind blown.
- title: 6 Month Retention
  image: retention
  desc: Most services keep your logs for 2 weeks, we start out with 6 month retention
    by default at no extra charge.
- title: Trending Events
  image: trending
  desc: Easily identify outliers, memory spikes and trending events with our advanced
    facets and graphs.
- title: 1 Click Heroku Install
  image: install
  desc: Just install our package and logs will automatically be parsed and sent to
    your dashboard, no configuration necessary.
billing_plans:
- name: Free
  image: free-plan
  price: 0
  data: 5
- name: Personal
  image: personal-plan
  price: 49
  data: 10
- name: Team
  image: team-plan
  price: 99
  data: 15
- name: Enterprise
  image: enterprise-plan
  price: 299
  data: 100+
faqs:
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- title: A question about Timber
  desc: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
team:
- name: Zach Sherman
  image: zach
  role: Founder & CEO
  desc: Founder @timberdotio, previously @seatgeek. @VanderbiltU grad. I like programming, design & sushi.
- name: Ben Johnson
  image: ben
  role: Founder & CTO
  desc: Founder / CTO @timberdotio, previously @seatgeek. I do things with computers.
- name: David Antaramian
  image: david
  role: Senior Backend Engineer
  desc: A curmudgeon that codes in @elixirlang and sometimes Ruby. Senior Backend Engineer at @timberdotio. Organizing @ElixirNYC. Treasuring @empexco.
- name: Garet McKinley
  image: garet
  role: Frontend Engineer
  desc: Writer of software. Designer of Vectors.
- name: You?
  image: bronson
  role: Lumberjack
  desc: Person of interest with a longer description about them that goes here.
footer:
- title: Features
  url: "/features/"
  desc: Logging made better
- title: Pricing
  url: "/pricing/"
  desc: Different package deals
- title: About
  url: "/about/"
  desc: What Timber is about
- title: Contact
  url: mailto://hi@timber.io
  desc: How to reach us
- title: Blog
  url: "/blog/"
  desc: Timber community posts
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
include:
- _pages
exclude:
- README.md
- vendor
gems:
- jekyll-paginate
- jekyll-seo-tag
